import 'package:flutter/material.dart';

class privacy extends StatelessWidget {
  const privacy({Key? key}) : super(key: key);
  static const routeName = '/about-us';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Privacy"),
        backgroundColor: Color.fromRGBO(7, 41, 77, 1),
      ),
      body: SingleChildScrollView(
        child: Container(
          child: Padding(
            padding: const EdgeInsets.all(13.0),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  "PRIVACY POLICY",
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                SizedBox(
                  height: 5,
                ),
                Text('Effective date: 2022-04-18'),
                SizedBox(
                  height: 10,
                ),
                Text(
                  '1. Introduction',
                  style: TextStyle(
                    fontSize: 16,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                Text(
                    'Welcome to faham.org.faham.org (“us”, “we”, or “our”) operates faham.org (hereinafter referred to as “Service”).Our Privacy Policy governs your visit to faham.org, and explains how we collect, safeguard and disclose information that results from your use of our Service.We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.Our Terms and Conditions (“Terms”) govern all use of our Service and together with the Privacy Policy constitutes your agreement with us (“agreement”).'),
                SizedBox(
                  height: 10,
                ),
                Text(
                  '2. Definitions',
                  style: TextStyle(
                    fontSize: 16,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                Text(
                    'SERVICE means the faham.org website operated by faham.orgPERSONAL DATA means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possessionUSAGE DATA is data collected automatically either generated by the use of Service or from Service infrastructure itself for example, the duration of a page visitCOOKIES are small files stored on your device (computer or mobile device).DATA CONTROLLER means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.DATA SUBJECT is any living individual who is the subject of Personal Data.THE USER is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.'),
                SizedBox(
                  height: 10,
                ),
                Text(
                  '3. Types of Data Collected',
                  style: TextStyle(
                    fontSize: 16,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                Text(
                    'Personal DataWhile using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (“Personal Data”). Personally identifiable information may include, but is not limited to:0.1. Email address0.2. First name and last name0.3. Phone number0.4. Address, Country, State, Province, ZIP/Postal code, City0.5. Cookies and Usage DataWe may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link.'),
                SizedBox(
                  height: 10,
                ),
                Text(
                  '4. Use of Data',
                  style: TextStyle(
                    fontSize: 16,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                Text(
                    'faham.org uses the collected data for various purposes: 0.1. to provide and maintain our Service; 0.2. to notify you about changes to our Service; 0.3. to allow you to participate in interactive features of our Service when you choose to do so; 0.4. to provide customer support; 0.5. to gather analysis or valuable information so that we can improve our Service; 0.6. to monitor the usage of our Service; 0.7. to detect, prevent and address technical issues; 0.8. to fulfil any other purpose for which you provide it; 0.9. to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection; 0.10. to provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.; 0.11. to provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information;'),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
